### ISSUE TITLE
Crash during discovering characteristics

### ISSUE THREAD

**Issue by pawelByszewski** [Polidea/FlutterBleLib#115]
```
I/zygote64(16758): Do full code cache collection, code=123KB, data=75KB
I/zygote64(16758): After code cache collection, code=112KB, data=62KB
I/flutter (16758): 2019-09-23T23:53:07.814009	D	DevicesBloc.startScan.<ac>:	 found new device CC2650 SensorTag 54:6C:0E:53:41:49
I/flutter (16758): 2019-09-23T23:53:07.878002	D	new DevicesList.<ac>:	 Build row for 0
I/flutter (16758): 2019-09-23T23:53:07.998489	D	new DevicesList.<ac>:	 Build row for 1
D/ViewRootImpl@7db6e3e[MainActivity](16758): ViewPostIme pointer 0
D/ViewRootImpl@7db6e3e[MainActivity](16758): ViewPostIme pointer 1
I/flutter (16758): 2019-09-23T23:53:17.630578	D	DevicesList._createTapListener.<ac>:	 clicked device: CC2650 SensorTag
I/flutter (16758): 2019-09-23T23:53:17.634110	D	DeviceListScreenState._onResume.<ac>:	 navigate to details
I/flutter (16758): 2019-09-23T23:53:17.634717	D	DeviceListScreenState._onPause:	 onPause
I/flutter (16758): 2019-09-23T23:53:17.640106	D	DevicesBloc.dispose:	 cancel _devicePickerSubscription
I/flutter (16758): 2019-09-23T23:53:17.695963	D	DeviceListScreenState.didChangeDependencies:	 DeviceListScreenState didChangeDependencies
I/flutter (16758): 2019-09-23T23:53:17.699269	D	DeviceListScreenState._onResume:	 onResume
I/flutter (16758): 2019-09-23T23:53:17.701940	D	DeviceDetailsBloc.init:	 init bloc
I/flutter (16758): 2019-09-23T23:53:17.706188	D	DeviceListScreenState.build:	 build DevicDetailsScreenState
I/flutter (16758): 2019-09-23T23:53:17.756811	D	new DevicesList.<ac>:	 Build row for 0
I/flutter (16758): 2019-09-23T23:53:17.764589	D	new DevicesList.<ac>:	 Build row for 1
I/flutter (16758): 2019-09-23T23:53:17.788421	D	DeviceDetailsBloc.init.<ac>:	 got bleDevice: DisconnectedBleDevice{} BleDevice{counter: 0, name: CC2650 SensorTag}
I/flutter (16758): 2019-09-23T23:53:17.792996	D	DeviceDetailsBloc.init.<ac>.<ac>:	 The device is connected: false
I/flutter (16758): set log level to debug
D/com.polidea.flutter_ble_lib.delegate.LogLevelDelegate(16758): set log level to: debug
I/flutter (16758): 2019-09-23T23:53:17.796832	D	DeviceDetailsBloc._connectTo:	 Try to connecto the device
D/RxBle#ClientOperationQueue(16758): QUEUED   ConnectOperation(143625037)
D/RxBle#ClientOperationQueue(16758): STARTED  ConnectOperation(143625037)
D/BluetoothGatt(16758): connect() - device: 54:6C:0E:53:41:49, auto: false
D/BluetoothAdapter(16758): isSecureModeEnabled
D/BluetoothGatt(16758): registerApp()
D/BluetoothGatt(16758): registerApp() - UUID=38047259-4632-4b2f-ae0a-a0deb53995bc
D/BluetoothGatt(16758): onClientRegistered() - status=0 clientIf=8
I/flutter (16758): deactivate
I/flutter (16758): 2019-09-23T23:53:18.018979	D	DeviceListScreenState.didChangeDependencies:	 DeviceListScreenState didChangeDependencies
I/flutter (16758): 2019-09-23T23:53:18.045402	D	DeviceListScreenState.build:	 build DeviceListScreenState
I/flutter (16758): 2019-09-23T23:53:18.060066	D	new DevicesList.<ac>:	 Build row for 0
I/flutter (16758): 2019-09-23T23:53:18.069412	D	new DevicesList.<ac>:	 Build row for 1
D/BluetoothGatt(16758): onClientConnectionState() - status=0 clientIf=8 device=54:6C:0E:53:41:49
D/RxBle#BluetoothGatt$1(16758): onConnectionStateChange newState=2 status=0
D/RxBle#ClientOperationQueue(16758): FINISHED ConnectOperation(143625037) in 338 ms
D/RxBle#ConnectionOperationQueue(16758): QUEUED   MtuRequestOperation(57662056)
D/RxBle#ConnectionOperationQueue(16758): STARTED  MtuRequestOperation(57662056)
D/BluetoothGatt(16758): configureMTU() - device: 54:6C:0E:53:41:49 mtu: 23
D/BluetoothGatt(16758): onConnectionUpdated() - Device=54:6C:0E:53:41:49 interval=6 latency=0 timeout=500 status=0
D/BluetoothGatt(16758): onConfigureMTU() - Device=54:6C:0E:53:41:49 mtu=23 status=0
D/RxBle#BluetoothGatt$1(16758): onMtuChanged mtu=23 status=0
D/RxBle#ConnectionOperationQueue(16758): FINISHED MtuRequestOperation(57662056) in 1848 ms
I/flutter (16758): 2019-09-23T23:53:20.037697	D	DeviceDetailsBloc._connectTo.<ac>:	 Observerd new connection state: PeripheralConnectionState.connected
I/flutter (16758): 2019-09-23T23:53:20.040626	D	DeviceDetailsBloc._connectTo:	 Connected to the device
D/RxBle#ConnectionOperationQueue(16758): QUEUED   ServiceDiscoveryOperation(200117109)
D/RxBle#ConnectionOperationQueue(16758): STARTED  ServiceDiscoveryOperation(200117109)
D/BluetoothGatt(16758): onConnectionUpdated() - Device=54:6C:0E:53:41:49 interval=39 latency=0 timeout=500 status=0
D/BluetoothGatt(16758): discoverServices() - device: 54:6C:0E:53:41:49
D/BluetoothGatt(16758): onSearchComplete() = Device=54:6C:0E:53:41:49 Status=0
D/RxBle#BluetoothGatt$1(16758): onServicesDiscovered status=0
D/RxBle#ConnectionOperationQueue(16758): FINISHED ServiceDiscoveryOperation(200117109) in 64 ms
E/MethodChannel#flutter_ble_lib(16758): Failed to handle method call
E/MethodChannel#flutter_ble_lib(16758): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/MethodChannel#flutter_ble_lib(16758): 	at com.polidea.flutter_ble_lib.delegate.DiscoveryDelegate.getCharacteristicsForService(DiscoveryDelegate.java:172)
E/MethodChannel#flutter_ble_lib(16758): 	at com.polidea.flutter_ble_lib.delegate.DiscoveryDelegate.onMethodCall(DiscoveryDelegate.java:70)
E/MethodChannel#flutter_ble_lib(16758): 	at com.polidea.flutter_ble_lib.FlutterBleLibPlugin.onMethodCall(FlutterBleLibPlugin.java:78)
E/MethodChannel#flutter_ble_lib(16758): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#flutter_ble_lib(16758): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#flutter_ble_lib(16758): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/MethodChannel#flutter_ble_lib(16758): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_ble_lib(16758): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#flutter_ble_lib(16758): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#flutter_ble_lib(16758): 	at android.app.ActivityThread.main(ActivityThread.java:6938)
E/MethodChannel#flutter_ble_lib(16758): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_ble_lib(16758): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/MethodChannel#flutter_ble_lib(16758): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
E/flutter (16758): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null)
E/flutter (16758): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter (16758): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter (16758): <asynchronous suspension>
E/flutter (16758): #2      _FlutterBleLib&FlutterBLE&DeviceConnectionMixin&ScanningMixin&LogLevelMixin&DiscoveryMixin.characteristicsForService (package:flutter_ble_lib/internal/bridge/discovery_mixin.dart:54:46)
E/flutter (16758): <asynchronous suspension>
E/flutter (16758): #3      InternalBleManager.characteristicsForService (package:flutter_ble_lib/internal/internal_ble_manager.dart:100:15)
E/flutter (16758): #4      Service.characteristics (package:flutter_ble_lib/service.dart:24:16)
E/flutter (16758): #5      DeviceDetailsBloc._connectTo.<anonymous closure> (package:flutter_ble_lib_example/device_details/device_details_bloc.dart:106:29)
E/flutter (16758): <asynchronous suspension>
E/flutter (16758): #6      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (16758): #7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (16758): #8      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter (16758): #9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter (16758): #10     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter (16758): #11     Future._complete (dart:async/future_impl.dart:473:7)
E/flutter (16758): #12     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (16758): #13     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
E/flutter (16758): #14     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
E/flutter (16758): #15     _FlutterBleLib&FlutterBLE&DeviceConnectionMixin&ScanningMixin&LogLevelMixin&DiscoveryMixin.services (package:flutter_ble_lib/internal/bridge/discovery_mixin.dart)
E/flutter (16758): <asynchronous suspension>
E/flutter (16758): #16     InternalBleManager.services (package:flutter_ble_lib/internal/internal_ble_manager.dart:89:15)
E/flutter (16758): #17     Peripheral.services (package:flutter_ble_lib/peripheral.dart:44:48)
E/flutter (16758): #18     DeviceDetailsBloc._connectTo.<anonymous closure> (package:flutter_ble_lib_example/device_details/device_details_bloc.dart:97:33)
E/flutter (16758): #19     _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (16758): #20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (16758): #21     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter (16758): #22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter (16758): #23     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter (16758): #24     Future._complete (dart:async/future_impl.dart:473:7)
E/flutter (16758): #25     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (16758): #26     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
E/flutter (16758): #27     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
E/flutter (16758): #28     _FlutterBleLib&FlutterBLE&DeviceConnectionMixin&ScanningMixin&LogLevelMixin&DiscoveryMixin.discoverAllServicesAndCharacteristics (package:flutter_ble_lib/internal/bridge/discovery_mixin.dart)
E/flutter (16758): <asynchronous suspension>
E/flutter (16758): #29     InternalBleManager.discoverAllServicesAndCharacteristics (package:flutter_ble_lib/internal/internal_ble_manager.dart:96:15)
E/flutter (16758): #30     Peripheral.discoverAllServicesAndCharacteristics (package:flutter_ble_lib/peripheral.dart:42:16)
E/flutter (16758): #31     DeviceDetailsBloc._connectTo (package:flutter_ble_lib_example/device_details/device_details_bloc.dart:96:10)
E/flutter (16758): <asynchronous suspension>
E/flutter (16758): #32     DeviceDetailsBloc.init.<anonymous closure>.<anonymous closure> (package:flutter_ble_lib_example/device_details/device_details_bloc.dart:53:11)
E/flutter (16758): #33     _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (16758): #34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (16758): #35     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter (16758): #36     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter (16758): #37     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter (16758): #38     Future._complete (dart:async/future_impl.dart:473:7)
E/flutter (16758): #39     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (16758): #40     _AsyncAwaitCompleter.comple

```

**Comment by mikolak** [comment]
Fixed by @bartoszwilk in #84
