### ISSUE TITLE
Compatibility with Dart 2.0 mode

### ISSUE THREAD

**Issue by PabloPL** [Polidea/FlutterBleLib#18]
When trying to run application with new flutter.io i'm getting following error
```
I/FlutterActivityDelegate(15704): onResume setting current activity to this
E/flutter (15704): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (15704): type 'Future<dynamic>' is not a subtype of type 'Future<Null>' where
E/flutter (15704):   Future is from dart:async
E/flutter (15704):   Future is from dart:async
E/flutter (15704):   Null is from dart:core
E/flutter (15704): 
E/flutter (15704): #0      FlutterBleLib.createClient (file:///home/pablo/.pub-cache/hosted/pub.dartlang.org/flutter_ble_lib-1.0.0/lib/source/lib_core.dart:38:26)
E/flutter (15704): #1      new MyApp (package:flutter_control_app/my_app.dart:8:28)
E/flutter (15704): #2      main (file:///home/pablo/AndroidStudioProjects/flutter_control_app/lib/main.dart:11:14)
E/flutter (15704): #3      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
E/flutter (15704): #4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```
Where i'm calling createClient with following way
```FlutterBleLib.instance.createClient(null)```

If i disable dart 2.0 mode, it's starting without errors

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.2.8, on Linux, locale pl_PL.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.22.2)
[✓] Connected devices (1 available)
```

Edit 1:
More details https://github.com/flutter/flutter/issues/15654 and https://github.com/pauldemarco/flutter_blue/issues/51

**Comment by JonathanSum** [comment]
So...we need wait for a fix? It looks like firebase or google sign in are affected.

**Comment by PabloPL** [comment]
With fix from https://github.com/Polidea/FlutterBleLib/pull/20 i was able to run and use example app.

**Comment by PabloPL** [comment]
For me it's working fine now. Closing.
